/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ADMIN_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_API_URL": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "AWS_SES_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AWS_SES_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": import("@cloudflare/workers-types").Service
    "AuthApi": import("@cloudflare/workers-types").Service
    "AuthStorage": import("@cloudflare/workers-types").KVNamespace
    "Bucket": import("@cloudflare/workers-types").R2Bucket
    "CLOUDFLARE_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_DEFAULT_ACCOUNT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Console": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
    "DISCORD_INCIDENT_WEBHOOK_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DISCORD_SUPPORT_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DISCORD_SUPPORT_CHANNEL_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "EMAILOCTOPUS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EnterpriseStorage": import("@cloudflare/workers-types").R2Bucket
    "FEISHU_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FEISHU_APP_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_APP_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_ID_CONSOLE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_SECRET_CONSOLE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HONEYCOMB_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HoneycombWebhookSecret": {
      "type": "random.index/randomPassword.RandomPassword"
      "value": string
    }
    "LogProcessor": import("@cloudflare/workers-types").Service
    "R2AccessKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "R2SecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SALESFORCE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SALESFORCE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SALESFORCE_INSTANCE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SUPPORT_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Stat": import("@cloudflare/workers-types").Service
    "Teams": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
    "UpstashRedisRestToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UpstashRedisRestUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.cloudflare.Astro"
      "url": string
    }
    "WebApp": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "ZEN_MODELS1": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS10": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS11": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS12": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS13": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS14": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS15": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS16": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS17": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS18": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS19": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS2": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS20": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS21": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS22": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS23": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS24": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS25": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS26": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS27": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS28": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS29": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS3": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS30": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS4": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS5": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS6": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS7": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS8": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS9": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_SESSION_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZenData": import("@cloudflare/workers-types").R2Bucket
    "ZenDataNew": import("@cloudflare/workers-types").R2Bucket
  }
}

import "sst"
export {}